/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Back: typeof import('./src/components/Back.vue')['default']
    EndContext: typeof import('./src/components/EndContext.vue')['default']
    Input: typeof import('./src/components/Form/Input.vue')['default']
    InputNumber: typeof import('./src/components/InputNumber.vue')['default']
    Overlay: typeof import('./src/components/Overlay.vue')['default']
    Popup: typeof import('./src/components/Popup/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
